#!/usr/bin/env zsh
# ---------------------------------------------------------------------------
# tools/generate-readme-svg.zsh — regenerate the README SVGs.
#
# Renders the REAL rtmux into SVG terminal windows. rtmux's whole job is to ask
# a remote host what it is running, so a screenshot of it is only worth anything
# if the rows came from a real tmux server — and they do: this builds two
# *local* tmux servers on private sockets (standing in for two remotes), seeds
# them with sessions, stubs `ssh` so it dispatches to them instead of a network,
# and runs rtmux **unmodified**. The rows, their colours, the header, the tab
# bar and the preview pane are genuine output. Only the window chrome around
# them, and fzf's own furniture, is drawn.
#
# Sibling of ccfind's / claude-profile's / claude-usage's
# tools/generate-readme-svg.zsh, from which the grid + emitter core here is
# borrowed; keep them roughly in sync. What is specific to rtmux:
#
#   * the sandbox is two real tmux servers, not a directory tree. Sessions run
#     a compiled do-nothing binary copied to the name we want tmux to report as
#     `pane_current_command` (`claude`, `zsh`) — the only portable way to make a
#     process *be* called something, since tmux reads the executable name and
#     ignores argv[0]. One session runs a real `vim`, which is what the preview
#     frame captures.
#   * rtmux's enrichment reads `~/.claude/sessions/<pid>.json`, so the seeding
#     step has to run *after* tmux forks the panes: the pid is the join key.
#   * the spinner short-circuits when stderr is not a terminal, and everything
#     downstream of it waits on a file the background job writes — so rtmux is
#     run on a pty rather than under plain redirection, or the listing races and
#     comes back empty. tmux needs one too, to attach the client that makes a
#     session show as attached.
#   * the stub `fzf` presses Tab for us: the tab bar is generated by helper
#     scripts whose paths only exist inside a live picker, so the stub runs the
#     ones named in fzf's own `--bind` argv to capture each tab's state before
#     rtmux's EXIT trap deletes them.
#   * one image is animated: the same captured material laid out as frames that
#     a CSS keyframe timeline steps through, so the README can show the fleet →
#     one host → one pane sequence instead of describing it. prefers-reduced-
#     motion freezes it on the preview frame.
#
# Usage:  zsh tools/generate-readme-svg.zsh
#           → assets/{demo,picker,multi,preview}-<hash>.svg, older ones deleted,
#             README <img> references rewritten (the random hash busts GitHub's
#             camo image cache). Commit all four files.
#         zsh tools/generate-readme-svg.zsh OUTDIR
#           → fixed names in OUTDIR, README untouched (for eyeballing a change).
#
# Needs: zsh, tmux, python3, vim and a C compiler (cc) — all of which a machine
# that develops rtmux already has. No network, and nothing outside the sandbox
# is read or written.
#
# Regenerate whenever the row format, the header text, the tab bar, the colours
# or these demo values change.
# ---------------------------------------------------------------------------
emulate -L zsh
setopt extended_glob

zmodload zsh/datetime

here=${0:a:h}
root=${here:h}

TMUX_BIN=$(command -v tmux)     || { print -u2 "generate-readme-svg: tmux not found"; exit 1 }
VIM_BIN=$(command -v vim)       || { print -u2 "generate-readme-svg: vim not found"; exit 1 }
CC_BIN=$(command -v cc)         || { print -u2 "generate-readme-svg: no C compiler (cc)"; exit 1 }
command -v python3 >/dev/null   || { print -u2 "generate-readme-svg: python3 not found"; exit 1 }

tmp=$(cd "$(mktemp -d)" && pwd -P)
SOCK_DEV="rtmux-svg-dev-$$"
SOCK_PROD="rtmux-svg-prod-$$"
cleanup() {
  # kill-server leaves the socket file behind, and this runs once per
  # invocation — so unlink them too rather than silting up the tmux tmpdir.
  local sockdir="${TMUX_TMPDIR:-/tmp}/tmux-$(id -u)"
  "$TMUX_BIN" -L "$SOCK_DEV"  kill-server 2>/dev/null
  "$TMUX_BIN" -L "$SOCK_PROD" kill-server 2>/dev/null
  rm -f "$sockdir/$SOCK_DEV" "$sockdir/$SOCK_PROD"
  rm -rf "$tmp"
}
trap cleanup EXIT INT TERM

# ---------------------------------------------------------------------------
# sandbox
# ---------------------------------------------------------------------------
# The terminal these are drawn in. The vim pane is created at the preview's
# inner width so its screen fills the box exactly, the way it would on a real
# remote whose pane you sized to your window.
integer COLS=112
integer PVCOLS=$(( COLS - 2 ))
integer PVROWS=12

bin="$tmp/bin"; stub="$tmp/stub"
mkdir -p "$bin" "$stub"

# A process is named by the file it was exec'd from — tmux reports that, not
# argv[0] — so the only way to have a pane whose `pane_current_command` is
# `claude` is for the running file to be called `claude`. Copying a system
# binary does not work (macOS kills a copy of a signed system executable), so
# compile a three-line one and copy *that* to each name we need.
print -r -- '#include <unistd.h>
int main(void) { for (;;) pause(); return 0; }' > "$tmp/idle.c"
"$CC_BIN" -O0 -o "$bin/_idle" "$tmp/idle.c" 2>/dev/null || {
  print -u2 "generate-readme-svg: could not compile the idle stub"; exit 1 }
local nm
for nm in claude zsh; do cp "$bin/_idle" "$bin/$nm"; done

# seed_claude <home> <socket> <session> <session-id> <status> <title>
# Writes the ~/.claude/sessions/<pid>.json that Claude Code writes per live
# process, plus the transcript rtmux reads the title out of. Must run after the
# pane exists: the pane's pid is what ties the two together, and it is the
# lookup rtmux actually performs (walking the pane's process tree, which on a
# host without /proc is the pane pid itself).
# NB: not `local home=` / `local status=` — zsh ties `home` to $HOME and makes
# `status` read-only, and both bite silently.
seed_claude() {
  local hdir=$1 sock=$2 sess=$3 sid=$4 state=$5 title=$6
  local pid cwd enc
  # `-t 0` is ambiguous — tmux tries it as a *window index* in the current
  # session before it tries it as a session name, so the auto-named sessions
  # (0, 1) resolve to the wrong pane and the titles land on the wrong rows.
  # `=<name>:` pins it: exact match, session target.
  pid=$("$TMUX_BIN" -L "$sock" display-message -p -t "=$sess:" '#{pane_pid}')
  cwd=$("$TMUX_BIN" -L "$sock" display-message -p -t "=$sess:" '#{pane_current_path}')
  mkdir -p "$hdir/.claude/sessions"
  printf '{"pid":%s,"sessionId":"%s","cwd":"%s","status":"%s","updatedAt":%s}\n' \
    "$pid" "$sid" "$cwd" "$state" "$EPOCHSECONDS" > "$hdir/.claude/sessions/$pid.json"
  enc=${cwd//\//-}
  mkdir -p "$hdir/.claude/projects/$enc"
  printf '{"type":"ai-title","aiTitle":"%s"}\n' "$title" \
    > "$hdir/.claude/projects/$enc/$sid.jsonl"
}

# --- pty helper -------------------------------------------------------------
# Two things here refuse to work off a terminal: rtmux's connect spinner (which
# returns immediately when stderr is not a tty, letting the code after it read a
# result file the background fetch has not written yet), and `tmux attach` (a
# client needs a terminal). `script(1)` is the usual answer but it copies the
# termios of *its own* stdin, so it dies with "tcgetattr/ioctl" the moment this
# runs anywhere that isn't an interactive shell — a CI job, an editor task, an
# agent. pty.fork() allocates the pty without touching our stdin at all.
# NB: not pty.py — a file of that name shadows the stdlib module it imports.
cat > "$tmp/ptyrun.py" <<'PYEOF'
import os, pty, sys, fcntl, termios, struct
argv = sys.argv[1:]
pid, fd = pty.fork()
if pid == 0:
    os.environ.setdefault("TERM", "xterm-256color")
    try:
        os.execvp(argv[0], argv)
    finally:
        os._exit(127)
fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 140, 0, 0))
while True:
    try:
        if not os.read(fd, 4096):
            break
    except OSError:
        break
os.waitpid(pid, 0)
PYEOF
onpty() { python3 "$tmp/ptyrun.py" "$@" }

# --- host "dev" -------------------------------------------------------------
DEV="$tmp/dev"
mkdir -p "$DEV/code/api-gateway" "$DEV/code/rtmux" "$DEV/etc/nginx"
"$TMUX_BIN" -L "$SOCK_DEV" kill-server 2>/dev/null

# The file the vim session has open — the preview frame is a genuine capture of
# this editor, so what it shows is this text.
cat > "$DEV/etc/nginx/ot.conf" <<'CONF'
server {
    listen 443 ssl http2;
    server_name ot.ichiva.no;

    include snippets/only-allow-homelab-networks.conf;

    location / {
        proxy_pass       http://quim-wg:7000;
        proxy_set_header Host       $host;
        proxy_set_header Upgrade    $http_upgrade;
    }
}
CONF

# tmux auto-names these 0 and 1 — which is the whole reason rtmux exists, so the
# demo has to show it.
"$TMUX_BIN" -L "$SOCK_DEV" new-session -d -x $COLS -y 20 -c "$DEV/code/api-gateway" "$bin/claude"
"$TMUX_BIN" -L "$SOCK_DEV" new-session -d -x $COLS -y 20 -c "$DEV/code/rtmux"       "$bin/claude"
TERM=xterm-256color "$TMUX_BIN" -L "$SOCK_DEV" new-session -d -s nginx \
  -x $PVCOLS -y $PVROWS -c "$DEV/etc/nginx" \
  "$VIM_BIN -u NONE -c 'syntax on' -c 'set ft=nginx' -c 'set nonumber' ot.conf"
sleep 1.5

seed_claude "$DEV" "$SOCK_DEV" 0 4f2c9a1e busy 'Fix the pagination race in the sync worker'
seed_claude "$DEV" "$SOCK_DEV" 1 7b3e05d4 idle 'Gate every fzf feature behind a version check'

# One session has to be attached, or every row shows the same dim ○ and the
# sort rule (unattached first) has nothing to demonstrate. A client needs a
# terminal, so borrow one from `script`. Attach to a session the preview never
# opens: a client resizes the session it joins, and the vim pane is sized to
# fill the preview box.
( onpty "$TMUX_BIN" -L "$SOCK_DEV" attach -t '=0:' >/dev/null 2>&1 & )
integer tries=0
until [[ -n $("$TMUX_BIN" -L "$SOCK_DEV" list-clients -F '#{client_tty}' 2>/dev/null) ]]; do
  (( ++tries > 50 )) && { print -u2 "generate-readme-svg: no tmux client attached"; exit 1 }
  sleep 0.1
done

# --- host "prod" ------------------------------------------------------------
PROD="$tmp/prod"
mkdir -p "$PROD/srv/ingest" "$PROD/srv"
"$TMUX_BIN" -L "$SOCK_PROD" kill-server 2>/dev/null
"$TMUX_BIN" -L "$SOCK_PROD" new-session -d -x $COLS -y 20 -c "$PROD/srv/ingest" "$bin/claude"
"$TMUX_BIN" -L "$SOCK_PROD" new-session -d -x $COLS -y 20 -s logs -c "$PROD/srv" "$bin/zsh"
sleep 1
seed_claude "$PROD" "$SOCK_PROD" 0 91ad7c60 idle 'Backfill the dedupe index after the schema bump'

# --- per-host tmux wrappers -------------------------------------------------
# The inspector shells out to a bare `tmux`; each host's wrapper pins it to that
# host's private socket, which is what makes two servers on one machine look
# like two machines.
local h
for h in dev prod; do
  mkdir -p "$tmp/wrap-$h"
  print -r -- "#!/bin/sh
exec ${(q)TMUX_BIN} -L $( [[ $h == dev ]] && print -n "$SOCK_DEV" || print -n "$SOCK_PROD" ) \"\$@\"" \
    > "$tmp/wrap-$h/tmux"
  chmod +x "$tmp/wrap-$h/tmux"
done

# --- stub ssh ---------------------------------------------------------------
# Every way rtmux reaches a host, answered locally: the ControlMaster probe
# (`true`), the inspector (`python3 -` with the script on stdin), the preview
# (`tmux capture-pane`), the directory query (`sh -s`), and `-O exit`. A host
# it was not told about is a connection this demo was not supposed to make.
cat > "$stub/ssh" <<'STUB'
#!/bin/sh
host=""
while [ $# -gt 0 ]; do
  case "$1" in
    -O) shift 2; exit 0 ;;
    -o) shift 2 ;;
    -*) shift ;;
    *)  host="$1"; shift; break ;;
  esac
done
eval "hh=\$RSVG_HOME_$host"; eval "ww=\$RSVG_WRAP_$host"
[ -n "$hh" ] || { echo "ssh: Could not resolve hostname $host" >&2; exit 255; }
case "$1" in
  true)    exit 0 ;;
  python3) shift; HOME="$hh" PATH="$ww:$PATH" exec python3 "$@" ;;
  tmux)    shift; HOME="$hh" exec "$ww/tmux" "$@" ;;
  sh)      shift; HOME="$hh" PATH="$ww:$PATH" exec sh "$@" ;;
esac
exit 1
STUB
chmod +x "$stub/ssh"

# --- stub fzf ---------------------------------------------------------------
# Records the rows and the argv the picker is handed, then exits 130 (fzf's
# "cancelled") so rtmux returns having selected nothing — no attach is ever
# attempted. With $RSVG_TABS set it also *presses Tab*: the tab bar is painted
# by helper scripts rtmux generates per run, and their paths are right there in
# fzf's own --bind argv, so running them is the same thing fzf would do — and it
# has to happen now, before rtmux's EXIT trap deletes them.
#
# Written before PATH is exported: zsh hashes the contents of every PATH
# directory, so a command created in an already-hashed dir stays invisible until
# a rehash — and the real fzf would then run against the operator's terminal.
cat > "$stub/fzf" <<'STUB'
#!/bin/sh
case "$1" in --version) echo "0.74.2 (stub)"; exit 0 ;; esac
printf '%s\n' "$@" > "$FZF_ARGS"
cat > "$FZF_CAPTURE"
if [ -n "$RSVG_TABS" ]; then
  adv=""; emit=""; hdr=""
  for a in "$@"; do
    case "$a" in
      tab:execute-silent*)
        # the action is `sh <adv> next` — stop at the space, or the path
        # comes back with " next" glued to it and `sh` looks for that file
        adv=$(printf '%s' "$a" | sed -n 's/^tab:execute-silent(sh \([^ )]*\).*/\1/p')
        emit=$(printf '%s' "$a" | sed -n 's/.*+reload(sh \([^)]*\))+transform-header.*/\1/p')
        hdr=$(printf '%s' "$a" | sed -n 's/.*+transform-header(sh \([^)]*\))$/\1/p')
        ;;
    esac
  done
  [ -n "$adv" ] || exit 130
  k=1
  while [ "$k" -le "$RSVG_TABS" ]; do
    sh "$adv" next
    sh "$emit" > "$FZF_CAPTURE.tab$k"
    sh "$hdr"  > "$FZF_CAPTURE.hdr$k"
    k=$(( k + 1 ))
  done
fi
exit 130
STUB
chmod +x "$stub/fzf"

export PATH="$stub:$PATH"
rehash
export RSVG_HOME_dev="$DEV"   RSVG_WRAP_dev="$tmp/wrap-dev"
export RSVG_HOME_prod="$PROD" RSVG_WRAP_prod="$tmp/wrap-prod"

# ---------------------------------------------------------------------------
# capture
# ---------------------------------------------------------------------------
# rtmux is run under `script`, i.e. on a pty. Not cosmetic: the connect spinner
# returns immediately when stderr is not a terminal, and the code after it reads
# a file the background fetch job has not written yet — off a pty the listing
# comes back empty every time.
run_rtmux() {   # <capture-file> <argv-file> <rtmux args...>
  local cap=$1 argf=$2; shift 2
  FZF_CAPTURE="$cap" FZF_ARGS="$argf" RTMUX_ENV_FILE=/dev/null \
  onpty zsh -c "source ${(q)root}/rtmux.zsh; rtmux $*" >/dev/null 2>&1
}

run_rtmux "$tmp/single" "$tmp/single.argv" dev
RSVG_TABS=2 run_rtmux "$tmp/multi" "$tmp/multi.argv" dev prod

# The preview. Not a hand-written capture-pane that resembles what rtmux would
# run — literally the --preview command rtmux handed fzf, with fzf's field
# placeholders filled from the row the demo highlights. That is the whole point:
# if rtmux's preview wiring were wrong, this would come back empty rather than
# quietly produce a plausible picture. (fzf expands {n} against the *original*
# line, not the --with-nth=1 display field, so {2}/{3}/{4} are the session, the
# slug and the host — verified against fzf 0.74.)
preview_cmd_for() {   # <argv-array> <raw-row>
  local -a av=("${(@P)1}")
  local -a f=("${(@ps:\t:)2}")
  local cmd="" a
  for a in "${av[@]}"; do [[ $a == --preview=* ]] && cmd=${a#--preview=}; done
  [[ -n $cmd ]] || return 1
  cmd=${cmd//\{1\}/${f[1]}}
  cmd=${cmd//\{2\}/${f[2]}}
  cmd=${cmd//\{3\}/${f[3]}}
  cmd=${cmd//\{4\}/${f[4]}}
  print -r -- "$cmd"
}

typeset -a srows margs mrows drows drows_raw
srows=("${(@f)$(<"$tmp/single")}");  srows=(${srows:#})
mrows=("${(@f)$(<"$tmp/multi")}");   mrows=(${mrows:#})
drows=("${(@f)$(<"$tmp/multi.tab1")}"); drows=(${drows:#})   # the "dev" tab
margs=("${(@f)$(<"$tmp/multi.argv")}")
drows_raw=("${drows[@]}")

# Only field 1 — the display line the inspector composes — is ever drawn. The
# session name (and, multi-host, the slug and host) are the fields fzf is told
# to hide with --with-nth=1, and they are what attach keys off.
srows=("${(@)srows%%$'\t'*}")
mrows=("${(@)mrows%%$'\t'*}")
drows=("${(@)drows%%$'\t'*}")

# The header fzf was handed. The multi-host one is two lines (tab bar + key
# hints), and the argv dump is one argument per line — so the continuation is a
# line of its own and has to be gathered, not just the --header= line taken.
argv_header() {
  local -a av=("${(@P)1}")
  local out="" a; integer i seen=0
  for (( i = 1; i <= ${#av}; i++ )); do
    a=${av[i]}
    if (( seen )); then
      [[ $a == --* ]] && break
      out+=$'\n'"$a"
    elif [[ $a == --header=* ]]; then
      out=${a#--header=}; seen=1
    fi
  done
  print -r -- "$out"
}
typeset -a sargs=("${(@f)$(<"$tmp/single.argv")}")
sheader=$(argv_header sargs)
mheader=$(argv_header margs)
dheader=$(<"$tmp/multi.hdr1")

[[ ${#srows} -ge 3 && ${#mrows} -ge 5 && ${#drows} -ge 3 && -n $sheader && -n $mheader && -n $dheader ]] || {
  print -u2 "generate-readme-svg: sandbox produced no output — aborting"
  print -u2 "  single=${#srows} multi=${#mrows} devtab=${#drows}"
  exit 1
}
print -u2 "captured ${#srows} single-host rows, ${#mrows} merged rows, ${#drows} on the dev tab"

# The row the story ends on: the vim session, found rather than counted, so the
# animation still points at the right one if the sort changes.
integer VIMROW=0 ri
for (( ri = 1; ri <= ${#drows_raw}; ri++ )); do
  [[ ${drows_raw[ri]} == *$'\t'nginx$'\t'* ]] && VIMROW=$ri
done
(( VIMROW )) || { print -u2 "generate-readme-svg: no nginx row on the dev tab"; exit 1 }

local pvcmd; pvcmd=$(preview_cmd_for margs "${drows_raw[VIMROW]}") || {
  print -u2 "generate-readme-svg: rtmux passed fzf no --preview"; exit 1 }
print -u2 "preview command (rtmux's own): $pvcmd"
preview_out=$(sh -c "$pvcmd" 2>/dev/null)
[[ -n $preview_out ]] || {
  print -u2 "generate-readme-svg: rtmux's own --preview command returned nothing"
  exit 1
}

# ---------------------------------------------------------------------------
# SVG
# ---------------------------------------------------------------------------
# Catppuccin Mocha chrome, matching the sibling generators.
BG='#1e1e2e'  BAR='#181825'  FG='#cdd6f4'  DIMC='#9399b2'
DOT1='#f38ba8' DOT2='#f9e2af' DOT3='#a6e3a1'
ACC='#89dceb'   # fzf's prompt string
PTR='#f38ba8'   # current-line marker bar
INFO='#f9e2af'  # match counter
RULE='#45475a'  # the rule on the info line, and the preview border
GUT='#313244'   # the gutter every list row carries
HL='#313244'    # current-line background
typeset -a ANSI_N ANSI_B
ANSI_N=('#45475a' '#f38ba8' '#a6e3a1' '#f9e2af' '#89b4fa' '#f5c2e7' '#94e2d5' '#bac2de')
ANSI_B=('#585b70' '#f38ba8' '#a6e3a1' '#f9e2af' '#89b4fa' '#f5c2e7' '#94e2d5' '#a6adc8')
FONT="'Cascadia Code','Fira Code',SFMono-Regular,Consolas,Menlo,monospace"
integer FS=13 LH=20 TH=30 PX=20 PY=14 SLACK=24 MINCOLS=52

# Terminal grid: every character is pinned to its own cell, so a row occupies
# exactly (columns × cw) in whichever font the renderer falls back to — which is
# what keeps the columns aligned in a browser that has none of these fonts.
typeset -a XCOL
local -F cw=7.85
integer k; local v
for (( k = 0; k <= 400; k++ )); do printf -v v '%.2f' $(( PX + k * cw )); XCOL[k+1]=$v; done
integer PANE=0
xrun() { print -rn -- "${(j: :)XCOL[PANE+$1+1,PANE+$1+$2]}" }
xat()  { print -rn -- "$XCOL[PANE+$1+1]" }
xesc() { local s=$1; s=${s//\&/&amp;}; s=${s//</&lt;}; s=${s//>/&gt;}; print -rn -- "$s" }

# Visible length of a line, ignoring SGR — what the grid must size to.
vlen() { local t=$1; t=${t//$'\e['[0-9;]#m/}; print -rn -- ${#t} }

# clip_ansi <line> <cols> — cut to <cols> *visible* columns, keeping the SGR
# runs that got us there (a terminal clips the drawing, not the state).
clip_ansi() {
  local s=$1 out="" pre esc; integer want=$2 seen=0 take
  while [[ -n $s ]]; do
    pre=${s%%$'\e'*}
    if [[ -n $pre ]]; then
      take=$(( want - seen ))
      (( take <= 0 )) && break
      if (( ${#pre} >= take )); then out+="${pre[1,take]}"; seen=$want; break; fi
      out+="$pre"; (( seen += ${#pre} ))
    fi
    s=${s[$(( ${#pre} + 1 )),-1]}
    [[ -n $s ]] || break
    esc=${s%%m*}m; out+="$esc"; s=${s[$(( ${#esc} + 1 )),-1]}
  done
  print -rn -- "$out"
}

# One SGR line → <tspan> runs, carrying bold/dim/reverse + colour across the
# line. Every run is pinned to its own columns so alignment survives font
# fallback. Reverse video (SGR 7) is drawn the way a terminal draws it: a filled
# rect in the foreground colour with the text knocked out in the background one
# — which is how rtmux marks the active host tab.
# Sets two globals rather than printing: RENDERED (the <tspan> runs) and
# REV_RECTS (the rects behind any reverse-video run). It must NOT be called as
# $(render_ansi …) — a subshell would swallow the second one, and the active tab
# comes out invisible: text knocked out in the background colour with nothing
# drawn behind it.
typeset -g REV_RECTS RENDERED
render_ansi() {
  local s=$1 out="" pre tail params pcode fill=""
  integer col=${2:-0} bold=0 dim=0 rev=0
  local cidx=""
  local -a parts
  REV_RECTS=""
  recompute() {
    if [[ -n $cidx ]]; then (( bold )) && fill=$ANSI_B[cidx+1] || fill=$ANSI_N[cidx+1]
    elif (( dim )); then fill=$DIMC
    else fill=""; fi
  }
  while [[ -n $s ]]; do
    pre=${s%%$'\e'*}
    if [[ -n $pre ]]; then
      if (( rev )); then
        REV_RECTS+="<rect x=\"$(xat col)\" y=\"@Y@\" width=\"$(( ${#pre} * cw + 0.5 ))\" height=\"$LH\" fill=\"${fill:-$FG}\"/>"
        out+="<tspan x=\"$(xrun col ${#pre})\" fill=\"$BG\">$(xesc "$pre")</tspan>"
      else
        out+="<tspan x=\"$(xrun col ${#pre})\"${fill:+ fill=\"$fill\"}>$(xesc "$pre")</tspan>"
      fi
      (( col += ${#pre} ))
    fi
    s=${s[$(( ${#pre} + 1 )),-1]}
    [[ -n $s ]] || break
    if [[ ${s[2]} == '[' ]]; then
      tail=${s#$'\e['}; params=${tail%%m*}
      s=${tail[$(( ${#params} + 2 )),-1]}
      parts=(${(s:;:)params}); (( ${#parts} )) || parts=(0)
      for pcode in $parts; do
        case $pcode in
          0)  bold=0; dim=0; rev=0; cidx="" ;;
          1)  bold=1 ;;
          2)  dim=1 ;;
          7)  rev=1 ;;
          <30-37>) cidx=$(( pcode - 30 )) ;;
          <90-97>) cidx=$(( pcode - 90 )); bold=1 ;;
          39) cidx="" ;;
        esac
      done
      recompute
    else
      s=${s[3,-1]}
    fi
  done
  RENDERED="$out"
}

# emit_lines <array-name> <y0> <x-offset> <width> — one pane's worth of lines.
# Entry format: TYPE|content, where
#   b = blank                     t = plain          c = dim
#   a = ANSI (terminal output)    h = fzf header     i = fzf match counter
#   n = list row                  p = current row    q = fzf prompt + cursor
#   x = shell input, block cursor parked after the last character
# Everything in the fzf frame except q sits at column 2, as fzf indents it.
emit_lines() {
  local -a _l=("${(@P)1}")
  integer y0=$2 W=$4
  PANE=$3
  local entry typ body T out=""
  integer i=0 y rx
  for entry in "${_l[@]}"; do
    typ=${entry%%\|*}; body=${entry#*|}
    y=$(( y0 + i * LH + FS ))
    T="  <text y=\"$y\" font-family=\"$FONT\" font-size=\"$FS\" xml:space=\"preserve\""
    case $typ in
      b) ;;
      t) out+="$T fill=\"$FG\"><tspan x=\"$(xrun 0 ${#body})\">$(xesc "$body")</tspan></text>"$'\n' ;;
      c) out+="$T fill=\"$DIMC\"><tspan x=\"$(xrun 0 ${#body})\">$(xesc "$body")</tspan></text>"$'\n' ;;
      a) render_ansi "$body"
         [[ -n $REV_RECTS ]] && out+="${REV_RECTS//@Y@/$(( y - FS - 3 ))}"$'\n'
         out+="$T fill=\"$FG\">$RENDERED</text>"$'\n' ;;
      h) render_ansi "$body" 2
         [[ -n $REV_RECTS ]] && out+="${REV_RECTS//@Y@/$(( y - FS - 3 ))}"$'\n'
         out+="$T fill=\"$FG\">$RENDERED</text>"$'\n' ;;
      i) # fzf's --separator draws the rule on the info line, from just past the
         # counter out to the right edge of the finder.
         rx=$(( PX + PANE * cw + (${#body} + 3) * cw ))
         out+="  <rect x=\"$rx\" y=\"$(( y - FS / 2 + 1 ))\" width=\"$(( W - rx - PX ))\" height=\"1\" fill=\"$RULE\"/>"$'\n'
         out+="$T fill=\"$INFO\"><tspan x=\"$(xrun 2 ${#body})\">$(xesc "$body")</tspan></text>"$'\n' ;;
      n) render_ansi "$body" 2
         out+="  <rect x=\"$(xat 0)\" y=\"$(( y - FS - 3 ))\" width=\"3\" height=\"$LH\" fill=\"$GUT\"/>"$'\n'
         out+="$T fill=\"$FG\">$RENDERED</text>"$'\n' ;;
      p) render_ansi "$body" 2
         out+="  <rect x=\"0\" y=\"$(( y - FS - 3 ))\" width=\"$W\" height=\"$LH\" fill=\"$HL\"/>"$'\n'
         out+="  <rect x=\"$(xat 0)\" y=\"$(( y - FS - 3 ))\" width=\"3\" height=\"$LH\" fill=\"$PTR\"/>"$'\n'
         out+="$T fill=\"$FG\">$RENDERED</text>"$'\n' ;;
      x) out+="  <rect x=\"$(xat ${#body})\" y=\"$(( y - FS + 1 ))\" width=\"8\" height=\"$(( FS + 3 ))\" fill=\"$FG\" opacity=\"0.75\"/>"$'\n'
         out+="$T fill=\"$FG\"><tspan x=\"$(xrun 0 ${#body})\">$(xesc "$body")</tspan></text>"$'\n' ;;
      q) out+="  <rect x=\"$(xat ${#body})\" y=\"$(( y - FS + 1 ))\" width=\"8\" height=\"$(( FS + 3 ))\" fill=\"$FG\" opacity=\"0.75\"/>"$'\n'
         out+="$T fill=\"$ACC\"><tspan x=\"$(xrun 0 ${#body})\">$(xesc "$body")</tspan></text>"$'\n' ;;
    esac
    (( i++ ))
  done
  PANE=0
  print -rn -- "$out"
}

# chrome <W> <H> <title> — the window: rounded body, title bar, traffic lights.
chrome() {
  integer W=$1 H=$2
  print -r -- "  <rect width=\"$W\" height=\"$H\" rx=\"10\" fill=\"$BG\"/>"
  print -r -- "  <rect width=\"$W\" height=\"$TH\" rx=\"10\" fill=\"$BAR\"/>"
  print -r -- "  <rect y=\"$(( TH - 6 ))\" width=\"$W\" height=\"6\" fill=\"$BAR\"/>"
  print -r -- "  <circle cx=\"18\" cy=\"$(( TH / 2 ))\" r=\"5.5\" fill=\"$DOT1\"/><circle cx=\"36\" cy=\"$(( TH / 2 ))\" r=\"5.5\" fill=\"$DOT2\"/><circle cx=\"54\" cy=\"$(( TH / 2 ))\" r=\"5.5\" fill=\"$DOT3\"/>"
  print -r -- "  <text x=\"$(( W / 2 ))\" y=\"$(( TH / 2 + 5 ))\" text-anchor=\"middle\" font-family=\"$FONT\" font-size=\"12\" fill=\"$DIMC\">$3</text>"
}

svg_open() {
  print -r -- "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"$1\" height=\"$2\" viewBox=\"0 0 $1 $2\" role=\"img\" aria-label=\"$(xesc "$3")\">"
}
svg_close() { print -r -- "</svg>" }

canvas_w() { print -rn -- $(( PX * 2 + $1 * cw + 6 + SLACK )) }
canvas_h() { print -rn -- $(( TH + PY + $1 * LH + PY )) }

# preview_box <y0> <cols> <lines> — fzf's preview border (rounded, its default)
# around the full-width pane rtmux opens with --preview-window=down.
preview_box() {
  integer x=$(( PX - 8 )) y=$(( $1 - 6 )) w=$(( $2 * cw + 16 )) h=$(( $3 * LH + 12 ))
  print -r -- "  <rect x=\"$x\" y=\"$y\" width=\"$w\" height=\"$h\" rx=\"6\" fill=\"none\" stroke=\"$RULE\" stroke-width=\"1\"/>"
}

# ---------------------------------------------------------------------------
# compose
# ---------------------------------------------------------------------------
# fzf_frame <out-array> <rows-array> <header> <current-index>
# The finder as --reverse lays it out: prompt, match counter, header (which for
# the multi-host picker is two lines — the tab bar and the key hints), rows.
fzf_frame() {
  local -a _rows=("${(@P)2}")
  local hdr=$3; integer cur=$4
  local -a out=("q|> " "i|${#_rows}/${#_rows}")
  local hl
  for hl in "${(@f)hdr}"; do out+=("h|$(clip_ansi "$hl" $(( COLS - 2 )))"); done
  integer ln
  for ln in {1..${#_rows}}; do
    if (( ln == cur )); then out+=("p|$(clip_ansi "${_rows[ln]}" $(( COLS - 2 )))")
    else                     out+=("n|$(clip_ansi "${_rows[ln]}" $(( COLS - 2 )))"); fi
  done
  set -A $1 "${out[@]}"
}

CMD_SINGLE='% rtmux dev'
CMD_MULTI='% rtmux dev prod'

typeset -a picker_lines multi_lines pv_lines pvlist_lines
fzf_frame picker_lines srows "$sheader" 1
picker_lines=("t|$CMD_SINGLE" 'b|' "${picker_lines[@]}")

fzf_frame multi_lines mrows "$mheader" 1
multi_lines=("t|$CMD_MULTI" 'b|' "${multi_lines[@]}")

# The preview pane, as fzf's `wrap` would not have to wrap it: the vim session
# was created at exactly the pane's inner width.
pv_lines=()
local ln
for ln in "${(@f)preview_out}"; do pv_lines+=("a|$(clip_ansi "$ln" $PVCOLS)"); done
while [[ ${pv_lines[-1]} == 'a|' ]]; do pv_lines[-1]=(); done

fzf_frame pvlist_lines drows "$dheader" $VIMROW
pvlist_lines=("t|$CMD_MULTI" 'b|' "${pvlist_lines[@]}")

# out_svg <file> <lines-array> <aria> [<pv-array>]
out_svg() {
  local file=$1 arr=$2 aria=$3 pvarr=${4:-}
  local -a _l=("${(@P)arr}")
  integer cols=0 n
  local e
  for e in "${_l[@]}"; do
    n=$(vlen "${e#*|}"); [[ ${e%%\|*} == (p|n|h|i) ]] && (( n += 2 ))
    (( n > cols )) && cols=$n
  done
  integer nlines=${#_l}
  local -a _pv
  if [[ -n $pvarr ]]; then
    _pv=("${(@P)pvarr}")
    for e in "${_pv[@]}"; do n=$(vlen "${e#*|}"); (( n > cols )) && cols=$n; done
    (( nlines += 1 + ${#_pv} ))
  fi
  (( cols < MINCOLS )) && cols=$MINCOLS
  integer W=$(canvas_w $cols) H=$(canvas_h $nlines)
  {
    svg_open $W $H "$aria"
    chrome $W $H 'rtmux'
    emit_lines $arr $(( TH + PY )) 0 $W
    if [[ -n $pvarr ]]; then
      integer pvy=$(( TH + PY + (${#_l} + 1) * LH ))
      preview_box $pvy $cols ${#_pv}
      emit_lines $pvarr $pvy 0 $W
    fi
    svg_close
  } > "$file"
}

# ---------------------------------------------------------------------------
# the animated one
# ---------------------------------------------------------------------------
# The same captured material laid out as frames on a CSS keyframe timeline: one
# <g> per frame, each visible for its slice of a looping cycle. No script — an
# SVG in an <img> (which is how GitHub serves a README asset, through camo) is
# rendered with scripting disabled but declarative animation live, so keyframes
# are the mechanism that actually survives the trip.
typeset -a f_spin f_all f_dev f_prev
# The one line here that is reconstructed rather than captured: the spinner
# prints only when stderr is a terminal and erases itself when the fetch lands,
# so there is nothing to capture. It is rtmux's own format string, with this
# run's host list.
f_spin=("t|$CMD_MULTI" 'b|' 'c|⠹ connecting to dev & prod…')
fzf_frame f_all  mrows "$mheader" 1
f_all=("t|$CMD_MULTI" 'b|' "${f_all[@]}")
fzf_frame f_dev  drows "$dheader" 1
f_dev=("t|$CMD_MULTI" 'b|' "${f_dev[@]}")
f_prev=("${pvlist_lines[@]}")

# One ↓ frame per row actually travelled, so the keycaps add up to where the
# cursor ends. Derived, not counted: the vim session's position depends on
# rtmux's sort, and a hard-coded single ↓ would quietly start lying if it moved.
typeset -a DOWNS
integer d
for (( d = 2; d <= VIMROW; d++ )); do
  fzf_frame "down$d" drows "$dheader" $d
  set -A "down$d" "t|$CMD_MULTI" 'b|' "${(@P)${:-down$d}}"
  DOWNS+=("down$d")
done

# The command types itself in: one frame per keystroke, block cursor parked
# after the last character. Same opacity mechanism as every other frame — no
# clip-path, no transform — so the typing rides on exactly the machinery that is
# already known to survive the trip through GitHub. The "% " is the prompt.
typeset -a FR FR_PV FR_KEY FR_DUR
CMD_TYPED=${CMD_MULTI#'% '}
integer ci
for (( ci = 0; ci < ${#CMD_TYPED}; ci++ )); do
  set -A "type$ci" "x|% ${CMD_TYPED[1,ci]}"
  FR+=("type$ci"); FR_PV+=(''); FR_KEY+=(''); FR_DUR+=(60)
done
FR+=("typed" ); set -A typed "x|$CMD_MULTI"; FR_PV+=(''); FR_KEY+=(''); FR_DUR+=(500)

# …then the run. Durations in milliseconds. The keycap names the key that
# produced the frame you are looking at.
FR+=(f_spin f_all f_dev)
FR_PV+=('' '' '')
FR_KEY+=('⏎' '' '⇥')
FR_DUR+=(900 1900 1700)
local dn
for dn in "${DOWNS[@]}"; do FR+=("$dn"); FR_PV+=(''); FR_KEY+=('↓'); FR_DUR+=(1100); done
FR+=(f_prev); FR_PV+=(pv_lines); FR_KEY+=('→'); FR_DUR+=(4600)

# keycap <W> <glyph> — the little pressed-key badge, top right under the bar.
keycap() {
  integer W=$1 x=$(( $1 - 58 )) y=$(( TH + 10 ))
  print -r -- "  <rect x=\"$x\" y=\"$y\" width=\"38\" height=\"26\" rx=\"6\" fill=\"$HL\" stroke=\"$RULE\"/>"
  print -r -- "  <text x=\"$(( x + 19 ))\" y=\"$(( y + 18 ))\" text-anchor=\"middle\" font-family=\"$FONT\" font-size=\"14\" fill=\"$FG\">$2</text>"
}

anim_svg() {
  local file=$1 aria=$2
  integer nlines=0 cols=0 n i j at
  local e arr pv
  for arr in "${FR[@]}"; do
    local -a _l=("${(@P)arr}")
    (( ${#_l} > nlines )) && nlines=${#_l}
    for e in "${_l[@]}"; do
      n=$(vlen "${e#*|}"); [[ ${e%%\|*} == (p|n|h|i) ]] && (( n += 2 ))
      (( n > cols )) && cols=$n
    done
  done
  for (( i = 1; i <= ${#FR}; i++ )); do
    pv=${FR_PV[i]}; [[ -n $pv ]] || continue
    local -a _p=("${(@P)pv}")
    local -a _f=("${(@P)${FR[i]}}")
    for e in "${_p[@]}"; do n=$(vlen "${e#*|}"); (( n > cols )) && cols=$n; done
    (( ${#_f} + 1 + ${#_p} > nlines )) && nlines=$(( ${#_f} + 1 + ${#_p} ))
  done
  integer W=$(canvas_w $cols) H=$(canvas_h $nlines)

  integer total=0
  for n in "${FR_DUR[@]}"; do (( total += n )); done

  {
    svg_open $W $H "$aria"
    # Each frame owns a window of the cycle, and the switch has to be a hard cut
    # — a terminal does not dissolve between states, and a frame that fades
    # leaves the one behind it showing through (the preview border ghosting over
    # the list, most visibly).
    #
    # step-end is what guarantees that. Writing two stops at the same percentage
    # does NOT: duplicate stops collapse to the last declaration, so
    # `0%,50%{opacity:0} 50%,100%{opacity:1}` is really "0 at 0%, 1 at 50%" and
    # the browser interpolates the whole way — a half-cycle cross-fade. With
    # step-end each value holds until the next stop, so one stop per switch says
    # exactly what it means.
    print -r -- "  <style>"
    print -r -- "    .fr{opacity:0}"
    at=0
    local -F p0 p1
    for (( j = 1; j <= ${#FR}; j++ )); do
      p0=$(( at * 100.0 / total ))
      (( at += FR_DUR[j] ))
      p1=$(( at * 100.0 / total ))
      print -r -- "    #fr$j{animation:k$j ${total}ms step-end infinite}"
      if (( j == 1 )); then
        printf '    @keyframes k%d{0%%{opacity:1}%.3f%%{opacity:0}}\n' $j $p1
      elif (( j == ${#FR} )); then
        printf '    @keyframes k%d{0%%{opacity:0}%.3f%%{opacity:1}}\n' $j $p0
      else
        printf '    @keyframes k%d{0%%{opacity:0}%.3f%%{opacity:1}%.3f%%{opacity:0}}\n' $j $p0 $p1
      fi
    done
    print -r -- "    @media (prefers-reduced-motion:reduce){.fr{animation:none!important;opacity:0}#fr${#FR}{opacity:1}}"
    print -r -- "  </style>"
    chrome $W $H 'rtmux'
    for (( j = 1; j <= ${#FR}; j++ )); do
      # opacity="0" as a presentation attribute on every frame but the LAST: CSS
      # (and therefore the animation) overrides it, so this changes nothing where
      # the timeline runs — but a renderer that ignores <style> altogether then
      # shows one frame instead of all of them stacked, and the one worth showing
      # is the final state, which is what prefers-reduced-motion picks too.
      print -r -- "  <g id=\"fr$j\" class=\"fr\"$( (( j < ${#FR} )) && print -n ' opacity=\"0\"')>"
      emit_lines ${FR[j]} $(( TH + PY )) 0 $W
      pv=${FR_PV[j]}
      if [[ -n $pv ]]; then
        local -a _p=("${(@P)pv}") _f=("${(@P)${FR[j]}}")
        integer pvy=$(( TH + PY + (${#_f} + 1) * LH ))
        preview_box $pvy $cols ${#_p}
        emit_lines $pv $pvy 0 $W
      fi
      [[ -n ${FR_KEY[j]} ]] && keycap $W "${FR_KEY[j]}"
      print -r -- "  </g>"
    done
    svg_close
  } > "$file"
}

# ---- output ----------------------------------------------------------------
DEMO_ARIA='rtmux running: the command typed out, a spinner connecting to two remotes, the merged picker listing every tmux session on both hosts with its project, process and Claude Code conversation title, Tab narrowing it to one host, the cursor moving down, and the preview pane opening on the live pane of the highlighted session'
PICKER_ARIA='the rtmux picker on a single host: three tmux sessions, each row an attached marker, the project directory, the pane process, and for the Claude Code sessions the conversation title, with the claude tag coloured by status'
MULTI_ARIA='the rtmux picker across two remotes: a tab bar reading All, dev, prod with All selected, above the merged session list, every row tagged with a coloured host column'
PREVIEW_ARIA='the rtmux picker with the preview pane open, showing the live content of the highlighted session pane — a vim buffer on the remote host — below the list'

if [[ -n ${1:-} ]]; then
  outdir=$1; mkdir -p "$outdir"
  anim_svg "$outdir/demo.svg"      "$DEMO_ARIA"
  out_svg  "$outdir/picker.svg"  picker_lines  "$PICKER_ARIA"
  out_svg  "$outdir/multi.svg"   multi_lines   "$MULTI_ARIA"
  out_svg  "$outdir/preview.svg" pvlist_lines  "$PREVIEW_ARIA" pv_lines
  print "wrote $outdir/{demo,picker,multi,preview}.svg"
else
  mkdir -p "$root/assets"
  for old in "$root"/assets/*-*.svg(N); do rm -f "$old"; done
  hash=$(xxd -l3 -p /dev/urandom)
  anim_svg "$root/assets/demo-${hash}.svg"      "$DEMO_ARIA"
  out_svg  "$root/assets/picker-${hash}.svg"  picker_lines "$PICKER_ARIA"
  out_svg  "$root/assets/multi-${hash}.svg"   multi_lines  "$MULTI_ARIA"
  out_svg  "$root/assets/preview-${hash}.svg" pvlist_lines "$PREVIEW_ARIA" pv_lines
  sed -i.bak \
    -e "s|assets/demo-[^)\"]*\.svg|assets/demo-${hash}.svg|" \
    -e "s|assets/picker-[^)\"]*\.svg|assets/picker-${hash}.svg|" \
    -e "s|assets/multi-[^)\"]*\.svg|assets/multi-${hash}.svg|" \
    -e "s|assets/preview-[^)\"]*\.svg|assets/preview-${hash}.svg|" \
    "$root/README.md" && rm -f "$root/README.md.bak"
  print "wrote assets/{demo,picker,multi,preview}-${hash}.svg and updated README.md"
fi
